id = "vscode-dark-modern-blurred"
name = "VSCode Dark Modern Blurred"
version = "0.1.6"
schema_version = 1
authors = ["sforman <sebastian@forman.no>"]
description = "VSCode Dark Modern Theme Blurred for Zed"
repository = "https://github.com/sf0rman/vscode_dark_modern_blurred.zed"
